### ISSUE TITLE
TESTS: Estimate package test coverage (and increase it)

### ISSUE THREAD

**Issue by HenrikBengtsson** [ropenscilabs/dirdf#7]
Use `covr::package_coverage()` to estimate package test coverage.  There are function we're not testing currently, e.g. we're testing `dirdf_parse()` but not `dirdf()`.

**Comment by seankross** [comment]
@HenrikBengtsson can you give me admin access so I can set up travis and covr?

**Comment by HenrikBengtsson** [comment]
It's actually @jennybc who set this one up.  While at it @jennybc, would you mind adding me as well?

**Comment by jennybc** [comment]
OK both @HenrikBengtsson and @seankross should have admin status on this repo now (was previously just "write").

**Comment by seankross** [comment]
Codecov is down :disappointed: so I'll try later today.

**Comment by HenrikBengtsson** [comment]
Thanks for adding Travis CI and Codecov.  (I've added the Codecov badge to README).
