### ISSUE TITLE
Move pathname to last column

### ISSUE THREAD

**Issue by HenrikBengtsson** [ropenscilabs/dirdf#8]
The pathnames are now in the first column returned by `dirdf()`, but since this is probably the information of least interested I think it should be moved to the last column instead.

**Comment by jennybc** [comment]
Specific problem this causes: original pathnames are, by definition, the longest, so hog all the space upon inspection, therefore the columns you most want to see end up in "Variables not shown" (at least in the dplyr/tibble printing world).
